default:
  host: localhost
  port: 6379

development:
  db: 0
  namespace: think_linkapp_dev

test:
  db: 1
  namespace: think_linkapp_test

production:
  db: 2
  host: 1432.1432.1324
  namespace: think_linkapp_production