source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'pg'
gem 'redis'
gem 'redis-namespace'
gem 'pry'
gem 'devise'
gem 'rack-cors', require: 'rack/cors'
gem 'puma'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'database_cleaner'
  gem 'debugger'
  gem 'shoulda-matchers'
end